services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    #dockerfile specifico per modalita sviluppo locale
       #sovrascrive il comando del dockerfile
    command: npm run start
    env_file: ".env"
    ports:
      - 3000:3000
    volumes:
    - ./frontend:/app # uso il volume app per avere l hot reload
    - /app/node_modules # Evita di sovrascrivere i moduli node
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      auth-service:
        condition: service_healthy
      products-service:
        condition: service_healthy
      scraper-service:
        condition: service_healthy
      transformer-service:
        condition: service_healthy
      orchestrator-service:
        condition: service_healthy
    # healthcheck:
    #   disable: true
    networks:
      - test

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    #sovrascrive il comando del dockerfile
    command: npm run dev
    env_file: ".env"
    ports:
      - 3030:3030
    volumes:
    - ./backend/auth-service:/app
    - /app/node_modules # Evita di sovrascrivere i moduli node
    restart: unless-stopped
    depends_on:
      db_auth:
        condition: service_healthy
    networks:
      - test

  products-service:
    build: ./backend/products-service
    container_name: products-service
       #sovrascrive il comando del dockerfile
    command: npm run dev
    env_file: ".env"
    ports:
      - 3020:3020
    volumes:
    - ./backend/products-service:/app # Monta il codice sorgente
    - /app/node_modules # Evita di sovrascrivere i moduli node
    restart: unless-stopped
    depends_on:
      db_auth:
        condition: service_healthy
    networks:
      - test

  scraper-service:
    build: ./backend/scraper-service
    container_name: scraper-service
    env_file: ".env"
    #command with --reload flag
    command: uvicorn main:app --host 0.0.0.0 --port 3040 --reload
    ports:
      - 3040:3040
    #volume mounted for hot reload
    volumes:
      - ./backend/scraper-service:/app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3040/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - test

  transformer-service:
    build: ./backend/transformer-service
    container_name: transformer-service
    env_file: ".env"
    command: uvicorn main:app --host 0.0.0.0 --port 3050 --reload
    ports:
      - 3050:3050
    volumes:
      - ./backend/transformer-service:/app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      db_products:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - test


  orchestrator-service:
    build: ./backend/orchestrator-service
    container_name: orchestrator-service
    env_file: ".env"
    command: uvicorn main:app --host 0.0.0.0 --port 3060 --reload
    ports:
      - 3060:3060
    volumes:
      - ./backend/orchestrator-service:/app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      db_products:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3060/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - test

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  db_auth:
    image: postgres:17-alpine3.22
    container_name: db_auth
    restart: always
    env_file: ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_AUTH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_AUTH}
      - POSTGRES_DB=${POSTGRES_DB_AUTH}
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./backend/auth-service/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - test

  db_products:
    image: postgres:17-alpine3.22
    container_name: db_products
    restart: always
    env_file: ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PRODUCTS}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PRODUCTS}
      - POSTGRES_DB=${POSTGRES_DB_PRODUCTS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_products_data:/var/lib/postgresql/data
      - ./backend/products-service/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - test

  # cron-service:
  #   build: ./cron-service
  #   container_name: cron-service
  #   depends_on:
  #     frontend:
  #       condition: service_healthy
  #   networks:
  #     - test

volumes:
  postgres_auth_data:
  postgres_products_data:

networks:
  test:
    driver: bridge
